version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    build: app
    expose:
      - "8080"
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
